title: Dahee Seminara # your name (or website title) here
logo: "/images/DaheeS.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>
  <a href="https://www.linkedin.com/in/dahee-seminara/">LinkedIn</a> 
  <br>
  <a href="https://github.com/daheeseminara/daheeseminara.github.io/tree/master/pdf/DaheeS_Resume.pdf" target="_blank">Resume</a>
  <br>
  <a href="https://www.GitHub.com/daheeseminara/">GitHub</a>  
  
  
theme: jekyll-theme-minimal
